codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "50...100"
  
  status:
    project:
      default:
        target: 60%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "*.pb.go"
  - "*.pulsar.go"
  - "**/*_test.go"
  - "**/testutil/**"
  - "**/mock_*.go"
  - "api/**"
  - "proto/**"
  - "test-keystore/**"
  - "infra/**"
  - "scripts/**"
  - "dependencies/**"

flags:
  unittests:
    carryforward: true
    paths:
      - "x/"
      - "app/"
      - "cmd/"
      - "types/"
      - "bindings/"

github_checks:
  annotations: true 