name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: input
    id: mitosis-version
    attributes:
      label: Mitosis Chain Version
      description: What version of Mitosis Chain are you running?
      placeholder: v1.0.0 or commit hash
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running on?
      options:
        - Localnet
        - Devnet
        - Testnet
        - Mainnet
        - Custom
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: Ubuntu 22.04, macOS 13.5, Windows 11, etc.
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: go version go1.21.5 linux/amd64
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Run command `...`
        2. Set configuration `...`
        3. Observe error `...`
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output.
      render: shell
      placeholder: Paste your logs here...
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide relevant configuration files or settings.
      render: yaml
      placeholder: Paste your configuration here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 