name: Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "good first issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! 📚
        
        Clear documentation is essential for a great developer experience.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - Setup Guide
        - CLI Documentation
        - Code Comments
        - Tutorial
        - FAQ
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Documentation Page/File
      description: Link to the documentation page or file path that needs improvement
      placeholder: https://docs.mitosis.org/... or path/to/file.md
    validations:
      required: false

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear instructions
        - Outdated content
        - Typo/Grammar
        - Broken links
        - Missing examples
        - Poor organization
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste relevant sections)
      render: markdown
      placeholder: Paste current documentation content here...
    validations:
      required: false

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: The documentation should explain...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Why is this improvement needed? What confusion does the current documentation cause?
      placeholder: This would help developers who...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to fixing this documentation issue?
      options:
        - label: I'd like to work on this documentation improvement
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 