name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '.go-version'
          cache: true

      - name: Build binaries
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          # Build mitosisd
          go build -o build/mitosisd-${GOOS}-${GOARCH} ./cmd/mitosisd
          
          # Build mito CLI
          go build -o build/mito-${GOOS}-${GOARCH} ./cmd/mito
          
          # Build midevtool
          go build -o build/midevtool-${GOOS}-${GOARCH} ./cmd/midevtool

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-amd64
          path: build/* 